# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: David Gilmore
email: dagilmore91@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Data | AI | Deep Learning | Coffee | Whiskey | Jazz | Rock Climbing
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dagilmore.com" # the base hostname & protocol for your site
twitter_username: dagilmore1
github_username:  dagilmore

# Build settings
markdown: kramdown
